name: cric
title: CRIC
base: core24
version: 'REPLACE_WITH_VERSION'
summary: A Java jlink ui - a Custom Runtime Image Creator
description: |
    **CRIC** is a gui for the Java jlink command.

    It produces custom runtime images, kind of Java Runtime Environments.

    The driver behind CRIC was the need to create cross-target custom runtime images for the non-modular application https://mapton.org.

    https://github.com/trixon/cric

grade: stable
platforms:
    amd64:
confinement: classic
icon: snap/gui/cric.png
license: Apache-2.0

apps:
  cric:
    command: cric/bin/cric

parts:
  cric:
    plugin: dump
    #source: https://github.com/trixon/cric/releases/download/v$SNAPCRAFT_PROJECT_VERSION/cric-$SNAPCRAFT_PROJECT_VERSION-linux.zip
    source: /root/project/cric-$SNAPCRAFT_PROJECT_VERSION-linux.zip
    source-type: zip

  config:
    after: [cric]
    plugin: nil
    override-prime: |
      craftctl default
      sed -i 's/${HOME}\/.${APPNAME}/${SNAP_USER_COMMON}\/.cric/' /root/prime/cric/bin/cric
      sed -i 's/${HOME}\/.cache\/${APPNAME}/${SNAP_USER_COMMON}\/.cache\/cric/' /root/prime/cric/bin/cric
      
lint:
  ignore: [library]
